### ISSUE TITLE
Compile build tool into and executable and reorganize tool versioning

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla-cli#28]
The build tool currently requires nodejs, yarn, and a c++ compiler to be installed on the system. It needs to check if it's dependancies are installed every time it runs and then install them if they aren't. This should all be simplified by pre-compiling binaries of the build processes and shipping them with the cli. This would remove the requirement for node, yarn, and the compiler.

This should be rather trivial with either [nexe](https://github.com/nexe/nexe) or [pkg](https://github.com/zeit/pkg). The largest reason why this wasn't done originally was because the bundling of native modules like `fs` and `node-sass` wasn't very good. This seems to have improved recently.

The build js is currently nested a bit deep too. There is a defunct entry point that should be removed  (this logic was moved into php.) Then each build process needs to be built into separate binaries and called from the php command.

**Comment by DaazKu** [comment]
I suggest that we move /src/Vanilla/FrontendTools to /src/Library/FrontedTools since the content of Vanilla should be php classes that belong to the namespace of the same name.

We can then put precompiled binaries in that Library folder and have the CLI commands have a dependency on them.

**Comment by Charrondev** [comment]
After attempting this in a few different ways the real issue is the binary size. Far too big to keep in a git repo, I'm going to close this out.
