### ISSUE TITLE
Add linter support for JS and SCSS

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla-cli#34]
The new base theme will have a new style standard for CSS and JS. We need to add support in vanilla-cli to use the linter config inside the new base theme. 

Eventually, when we're satisfied with it, we can move it into vanilla-cli and version it, so the config will be the same across vanilla.

**Comment by Charrondev** [comment]
**Requirements**
- [ ] Separate command `vanilla lint` `vanilla lint --watch`
- [ ] Flag for the build process `vanilla build --lint --watch`
- [ ] Loads configs defined in an addon
- [ ] Capable of writing custom rules for both the style linter and the javascript linter

**Future**
- [ ] Versioning Support (separate or tied to a processVersion)
- [ ] Configs moved to [vanilla/standards](https://github.com/vanilla/standards) and required as dependancies

I'm leaning towards [ESLint](https://eslint.org/) for the JS
- Ability to write custom rules easily
- Formatting Support
- Support for all ES2017+ features
- Support for React, JSX, and Flow
- Large amount of community support

I'm less opinionated about the style linter but lean towards [StyleLint](https://github.com/stylelint/stylelint)
- Custom rules
- Parses any CSS-like syntax
- Powered by PostCSS (the thing autoprefixer is built on)
- Formatting support
